import { SpeedyCountry } from "./types/speedy";

export const speedyCountries: SpeedyCountry[] = [
  {
    id: 36,
    name: "АВСТРАЛИЯ",
    nameEn: "AUSTRALIA",
    isoAlpha2: "AU",
    isoAlpha3: "AUS",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 40,
    name: "АВСТРИЯ",
    nameEn: "AUSTRIA",
    isoAlpha2: "AT",
    isoAlpha3: "AUT",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 31,
    name: "АЗЕРБАЙДЖАН",
    nameEn: "AZERBAIJAN",
    isoAlpha2: "AZ",
    isoAlpha3: "AZE",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 8,
    name: "АЛБАНИЯ",
    nameEn: "ALBANIA",
    isoAlpha2: "AL",
    isoAlpha3: "ALB",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 12,
    name: "АЛЖИР",
    nameEn: "ALGERIA",
    isoAlpha2: "DZ",
    isoAlpha3: "DZA",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 16,
    name: "АМЕРИКАНСКА САМОА",
    nameEn: "AMERICAN SAMOA",
    isoAlpha2: "AS",
    isoAlpha3: "ASM",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 850,
    name: "АМЕРИКАНСКИ ВИРДЖИНСКИ ОСТРОВИ",
    nameEn: "VIRGIN ISLANDS (U.S.)",
    isoAlpha2: "VI",
    isoAlpha3: "VIR",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 24,
    name: "АНГОЛА",
    nameEn: "ANGOLA",
    isoAlpha2: "AO",
    isoAlpha3: "AGO",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 660,
    name: "АНГУИЛА",
    nameEn: "ANGUILLA",
    isoAlpha2: "AI",
    isoAlpha3: "AIA",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 20,
    name: "АНДОРА",
    nameEn: "ANDORRA",
    isoAlpha2: "AD",
    isoAlpha3: "AND",
    postCodeFormats: "NNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 10,
    name: "АНТАРКТИДА",
    nameEn: "ANTARCTICA",
    isoAlpha2: "AQ",
    isoAlpha3: "ATA",
    postCodeFormats: "NNNNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 28,
    name: "АНТИГУА И БАРБУДА",
    nameEn: "ANTIGUA AND BARBUDA",
    isoAlpha2: "AG",
    isoAlpha3: "ATG",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 32,
    name: "АРЖЕНТИНА",
    nameEn: "ARGENTINA",
    isoAlpha2: "AR",
    isoAlpha3: "ARG",
    postCodeFormats: "ANNNNBBB",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 51,
    name: "АРМЕНИЯ",
    nameEn: "ARMENIA",
    isoAlpha2: "AM",
    isoAlpha3: "ARM",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 533,
    name: "АРУБА",
    nameEn: "ARUBA",
    isoAlpha2: "AW",
    isoAlpha3: "ABW",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 4,
    name: "АФГАНИСТАН",
    nameEn: "AFGHANISTAN",
    isoAlpha2: "AF",
    isoAlpha3: "AFG",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 50,
    name: "БАНГЛАДЕШ",
    nameEn: "BANGLADESH",
    isoAlpha2: "BD",
    isoAlpha3: "BGD",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 52,
    name: "БАРБАДОС",
    nameEn: "BARBADOS",
    isoAlpha2: "BB",
    isoAlpha3: "BRB",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 44,
    name: "БАХАМСКИ ОСТРОВИ",
    nameEn: "BAHAMAS",
    isoAlpha2: "BS",
    isoAlpha3: "BHS",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 48,
    name: "БАХРЕЙН",
    nameEn: "BAHRAIN",
    isoAlpha2: "BH",
    isoAlpha3: "BHR",
    postCodeFormats: "NNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 112,
    name: "БЕЛАРУС",
    nameEn: "BELARUS",
    isoAlpha2: "BY",
    isoAlpha3: "BLR",
    postCodeFormats: "NNNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 56,
    name: "БЕЛГИЯ",
    nameEn: "BELGIUM",
    isoAlpha2: "BE",
    isoAlpha3: "BEL",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 84,
    name: "БЕЛИЗ",
    nameEn: "BELIZE",
    isoAlpha2: "BZ",
    isoAlpha3: "BLZ",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 204,
    name: "БЕНИН",
    nameEn: "BENIN",
    isoAlpha2: "BJ",
    isoAlpha3: "BEN",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 60,
    name: "БЕРМУДСКИ ОСТРОВИ",
    nameEn: "BERMUDA",
    isoAlpha2: "BM",
    isoAlpha3: "BMU",
    postCodeFormats: "AANN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 68,
    name: "БОЛИВИЯ",
    nameEn: "BOLIVIA",
    isoAlpha2: "BO",
    isoAlpha3: "BOL",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 70,
    name: "БОСНА И ХЕРЦЕГОВИНА",
    nameEn: "BOSNIA AND HERZEGOWINA",
    isoAlpha2: "BA",
    isoAlpha3: "BIH",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 72,
    name: "БОТСВАНА",
    nameEn: "BOTSWANA",
    isoAlpha2: "BW",
    isoAlpha3: "BWA",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 76,
    name: "БРАЗИЛИЯ",
    nameEn: "BRAZIL",
    isoAlpha2: "BR",
    isoAlpha3: "BRA",
    postCodeFormats: "NNNNNOOO",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 86,
    name: "БРИТАНСКА ИНДООКЕАНСКА ТЕРИТОРИЯ",
    nameEn: "BRITISH INDIAN OCEAN TERRITORY",
    isoAlpha2: "IO",
    isoAlpha3: "IOT",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 92,
    name: "БРИТАНСКИ ВИРДЖИНСКИ ОСТРОВИ",
    nameEn: "VIRGIN ISLANDS (BRITISH)",
    isoAlpha2: "VG",
    isoAlpha3: "VGB",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 96,
    name: "БРУНЕЙ",
    nameEn: "BRUNEI DARUSSALAM",
    isoAlpha2: "BN",
    isoAlpha3: "BRN",
    postCodeFormats: "AANNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 854,
    name: "БУРКИНА ФАСО",
    nameEn: "BURKINA FASO",
    isoAlpha2: "BF",
    isoAlpha3: "BFA",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 108,
    name: "БУРУНДИ",
    nameEn: "BURUNDI",
    isoAlpha2: "BI",
    isoAlpha3: "BDI",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 64,
    name: "БУТАН",
    nameEn: "BHUTAN",
    isoAlpha2: "BT",
    isoAlpha3: "BTN",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 100,
    name: "БЪЛГАРИЯ",
    nameEn: "BULGARIA",
    isoAlpha2: "BG",
    isoAlpha3: "BGR",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 1,
    currencyCode: "BGN",
    defaultOfficeId: null,
    streetTypes: "бул.,ул.,пл.,ал.,мост",
    streetTypesEn: "bul.,ul.,pl.,al.,most",
    complexTypes: "кв.,м.,жк,мах.,в.з.,парк,п.з.",
    complexTypesEn: "kv.,m.,zhk,mah.,v.z.,park,p.z.",
    siteNomen: 1,
  },
  {
    id: 548,
    name: "ВАНУАТУ",
    nameEn: "VANUATU",
    isoAlpha2: "VU",
    isoAlpha3: "VUT",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 336,
    name: "ВАТИКАН",
    nameEn: "VATICAN CITY STATE (HOLY SEE)",
    isoAlpha2: "VA",
    isoAlpha3: "VAT",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 826,
    name: "ВЕЛИКОБРИТАНИЯ",
    nameEn: "UNITED KINGDOM",
    isoAlpha2: "GB",
    isoAlpha3: "GBR",
    postCodeFormats: "ANNAA,A??NAA,AAN?NAA",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 862,
    name: "ВЕНЕЦУЕЛА",
    nameEn: "VENEZUELA",
    isoAlpha2: "VE",
    isoAlpha3: "VEN",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 704,
    name: "ВИЕТНАМ",
    nameEn: "VIET NAM",
    isoAlpha2: "VN",
    isoAlpha3: "VNM",
    postCodeFormats: "NNNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 266,
    name: "ГАБОН",
    nameEn: "GABON",
    isoAlpha2: "GA",
    isoAlpha3: "GAB",
    postCodeFormats: "NN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 270,
    name: "ГАМБИЯ",
    nameEn: "GAMBIA",
    isoAlpha2: "GM",
    isoAlpha3: "GMB",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 288,
    name: "ГАНА",
    nameEn: "GHANA",
    isoAlpha2: "GH",
    isoAlpha3: "GHA",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 312,
    name: "ГВАДЕЛУПА",
    nameEn: "GUADELOUPE",
    isoAlpha2: "GP",
    isoAlpha3: "GLP",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 320,
    name: "ГВАТЕМАЛА",
    nameEn: "GUATEMALA",
    isoAlpha2: "GT",
    isoAlpha3: "GTM",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 328,
    name: "ГВИАНА",
    nameEn: "GUYANA",
    isoAlpha2: "GY",
    isoAlpha3: "GUY",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 324,
    name: "ГВИНЕЯ",
    nameEn: "GUINEA",
    isoAlpha2: "GN",
    isoAlpha3: "GIN",
    postCodeFormats: "NNNBBOOO",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 624,
    name: "ГВИНЕЯ-БИСАУ",
    nameEn: "GUINEA-BISSAU",
    isoAlpha2: "GW",
    isoAlpha3: "GNB",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 276,
    name: "ГЕРМАНИЯ",
    nameEn: "GERMANY",
    isoAlpha2: "DE",
    isoAlpha3: "DEU",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 292,
    name: "ГИБРАЛТАР",
    nameEn: "GIBRALTAR",
    isoAlpha2: "GI",
    isoAlpha3: "GIB",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 308,
    name: "ГРЕНАДА",
    nameEn: "GRENADA",
    isoAlpha2: "GD",
    isoAlpha3: "GRD",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 304,
    name: "ГРЕНЛАНДИЯ",
    nameEn: "GREENLAND",
    isoAlpha2: "GL",
    isoAlpha3: "GRL",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 268,
    name: "ГРУЗИЯ",
    nameEn: "GEORGIA",
    isoAlpha2: "GE",
    isoAlpha3: "GEO",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 316,
    name: "ГУАМ",
    nameEn: "GUAM",
    isoAlpha2: "GU",
    isoAlpha3: "GUM",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 831,
    name: "ГЪРНСИ",
    nameEn: "GUERNSEY",
    isoAlpha2: "GG",
    isoAlpha3: "GGY",
    postCodeFormats: "ANNAA,A??NAA,AAN?NAA",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 300,
    name: "ГЪРЦИЯ",
    nameEn: "GREECE",
    isoAlpha2: "GR",
    isoAlpha3: "GRC",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "EUR",
    defaultOfficeId: 52,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 208,
    name: "ДАНИЯ",
    nameEn: "DENMARK",
    isoAlpha2: "DK",
    isoAlpha3: "DNK",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 180,
    name: "ДЕМОКРАТИЧНА РЕПУБЛИКА КОНГО",
    nameEn: "CONGO, DEMOCRATIC REPUBLIC OF (WAS ZAIRE)",
    isoAlpha2: "CD",
    isoAlpha3: "COD",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 262,
    name: "ДЖИБУТИ",
    nameEn: "DJIBOUTI",
    isoAlpha2: "DJ",
    isoAlpha3: "DJI",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 832,
    name: "ДЖЪРСИ",
    nameEn: "JERSEY",
    isoAlpha2: "JE",
    isoAlpha3: "JEY",
    postCodeFormats: "ANNAA,A??NAA,AAN?NAA",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 212,
    name: "ДОМИНИКА",
    nameEn: "DOMINICA",
    isoAlpha2: "DM",
    isoAlpha3: "DMA",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 214,
    name: "ДОМИНИКАНСКА РЕПУБЛИКА",
    nameEn: "DOMINICAN REPUBLIC",
    isoAlpha2: "DO",
    isoAlpha3: "DOM",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 818,
    name: "ЕГИПЕТ",
    nameEn: "EGYPT",
    isoAlpha2: "EG",
    isoAlpha3: "EGY",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 218,
    name: "ЕКВАДОР",
    nameEn: "ECUADOR",
    isoAlpha2: "EC",
    isoAlpha3: "ECU",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 226,
    name: "ЕКВАТОРИАЛНА ГВИНЕЯ",
    nameEn: "EQUATORIAL GUINEA",
    isoAlpha2: "GQ",
    isoAlpha3: "GNQ",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 222,
    name: "ЕЛ САЛВАДОР",
    nameEn: "EL SALVADOR",
    isoAlpha2: "SV",
    isoAlpha3: "SLV",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 232,
    name: "ЕРИТРЕЯ",
    nameEn: "ERITREA",
    isoAlpha2: "ER",
    isoAlpha3: "ERI",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 233,
    name: "ЕСТОНИЯ",
    nameEn: "ESTONIA",
    isoAlpha2: "EE",
    isoAlpha3: "EST",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 231,
    name: "ЕТИОПИЯ",
    nameEn: "ETHIOPIA",
    isoAlpha2: "ET",
    isoAlpha3: "ETH",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 894,
    name: "ЗАМБИЯ",
    nameEn: "ZAMBIA",
    isoAlpha2: "ZM",
    isoAlpha3: "ZMB",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 732,
    name: "ЗАПАДНА САХАРА",
    nameEn: "WESTERN SAHARA",
    isoAlpha2: "EH",
    isoAlpha3: "ESH",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 716,
    name: "ЗИМБАБВЕ",
    nameEn: "ZIMBABWE",
    isoAlpha2: "ZW",
    isoAlpha3: "ZWE",
    postCodeFormats: "NNNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 376,
    name: "ИЗРАЕЛ",
    nameEn: "ISRAEL",
    isoAlpha2: "IL",
    isoAlpha3: "ISR",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 626,
    name: "ИЗТОЧЕН ТИМОР",
    nameEn: "EAST TIMOR",
    isoAlpha2: "TL",
    isoAlpha3: "TLS",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 356,
    name: "ИНДИЯ",
    nameEn: "INDIA",
    isoAlpha2: "IN",
    isoAlpha3: "IND",
    postCodeFormats: "NNNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 360,
    name: "ИНДОНЕЗИЯ",
    nameEn: "INDONESIA",
    isoAlpha2: "ID",
    isoAlpha3: "IDN",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 368,
    name: "ИРАК",
    nameEn: "IRAQ",
    isoAlpha2: "IQ",
    isoAlpha3: "IRQ",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 364,
    name: "ИРАН",
    nameEn: "IRAN (ISLAMIC REPUBLIC OF)",
    isoAlpha2: "IR",
    isoAlpha3: "IRN",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 372,
    name: "ИРЛАНДИЯ",
    nameEn: "IRELAND",
    isoAlpha2: "IE",
    isoAlpha3: "IRL",
    postCodeFormats: "N",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 352,
    name: "ИСЛАНДИЯ",
    nameEn: "ICELAND",
    isoAlpha2: "IS",
    isoAlpha3: "ISL",
    postCodeFormats: "NNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 724,
    name: "ИСПАНИЯ",
    nameEn: "SPAIN",
    isoAlpha2: "ES",
    isoAlpha3: "ESP",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 380,
    name: "ИТАЛИЯ",
    nameEn: "ITALY",
    isoAlpha2: "IT",
    isoAlpha3: "ITA",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 887,
    name: "ЙЕМЕН",
    nameEn: "YEMEN",
    isoAlpha2: "YE",
    isoAlpha3: "YEM",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 400,
    name: "ЙОРДАНИЯ",
    nameEn: "JORDAN",
    isoAlpha2: "JO",
    isoAlpha3: "JOR",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 132,
    name: "КАБО ВЕРДЕ",
    nameEn: "CAPE VERDE",
    isoAlpha2: "CV",
    isoAlpha3: "CPV",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 398,
    name: "КАЗАХСТАН",
    nameEn: "KAZAKHSTAN",
    isoAlpha2: "KZ",
    isoAlpha3: "KAZ",
    postCodeFormats: "NNNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 136,
    name: "КАЙМАНОВИ ОСТРОВИ",
    nameEn: "CAYMAN ISLANDS",
    isoAlpha2: "KY",
    isoAlpha3: "CYM",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 116,
    name: "КАМБОДЖА",
    nameEn: "CAMBODIA",
    isoAlpha2: "KH",
    isoAlpha3: "KHM",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 120,
    name: "КАМЕРУН",
    nameEn: "CAMEROON",
    isoAlpha2: "CM",
    isoAlpha3: "CMR",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 124,
    name: "КАНАДА",
    nameEn: "CANADA",
    isoAlpha2: "CA",
    isoAlpha3: "CAN",
    postCodeFormats: "ANANAN",
    requireState: true,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 991,
    name: "КАНАРСКИ ОСТРОВИ",
    nameEn: "CANARY ISLANDS",
    isoAlpha2: "IC",
    isoAlpha3: "ISC",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 634,
    name: "КАТАР",
    nameEn: "QATAR",
    isoAlpha2: "QA",
    isoAlpha3: "QAT",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 404,
    name: "КЕНИЯ",
    nameEn: "KENYA",
    isoAlpha2: "KE",
    isoAlpha3: "KEN",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 196,
    name: "КИПЪР",
    nameEn: "CYPRUS",
    isoAlpha2: "CY",
    isoAlpha3: "CYP",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "EUR",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 417,
    name: "КИРГИЗСТАН",
    nameEn: "KYRGYZSTAN",
    isoAlpha2: "KG",
    isoAlpha3: "KGZ",
    postCodeFormats: "NNNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 296,
    name: "КИРИБАТИ",
    nameEn: "KIRIBATI",
    isoAlpha2: "KI",
    isoAlpha3: "KIR",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 156,
    name: "КИТАЙ",
    nameEn: "CHINA",
    isoAlpha2: "CN",
    isoAlpha3: "CHN",
    postCodeFormats: "NNNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 166,
    name: "КОКОСОВИ ОСТРОВИ",
    nameEn: "COCOS (KEELING) ISLANDS",
    isoAlpha2: "CC",
    isoAlpha3: "CCK",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 162,
    name: "КОЛЕДЕН ОСТРОВ",
    nameEn: "CHRISTMAS ISLAND",
    isoAlpha2: "CX",
    isoAlpha3: "CXR",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 170,
    name: "КОЛУМБИЯ",
    nameEn: "COLOMBIA",
    isoAlpha2: "CO",
    isoAlpha3: "COL",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 174,
    name: "КОМОРСКИ ОСТРОВИ",
    nameEn: "COMOROS",
    isoAlpha2: "KM",
    isoAlpha3: "COM",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 188,
    name: "КОСТА РИКА",
    nameEn: "COSTA RICA",
    isoAlpha2: "CR",
    isoAlpha3: "CRI",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 384,
    name: "КОТ Д'ИВОАР",
    nameEn: "COTE D'IVOIRE",
    isoAlpha2: "CI",
    isoAlpha3: "CIV",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 192,
    name: "КУБА",
    nameEn: "CUBA",
    isoAlpha2: "CU",
    isoAlpha3: "CUB",
    postCodeFormats: "N,NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 414,
    name: "КУВЕЙТ",
    nameEn: "KUWAIT",
    isoAlpha2: "KW",
    isoAlpha3: "KWT",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 418,
    name: "ЛАОС",
    nameEn: "LAO PEOPLE'S DEMOCRATIC REPUBLIC",
    isoAlpha2: "LA",
    isoAlpha3: "LAO",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 428,
    name: "ЛАТВИЯ",
    nameEn: "LATVIA",
    isoAlpha2: "LV",
    isoAlpha3: "LVA",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 426,
    name: "ЛЕСОТО",
    nameEn: "LESOTHO",
    isoAlpha2: "LS",
    isoAlpha3: "LSO",
    postCodeFormats: "NNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 430,
    name: "ЛИБЕРИЯ",
    nameEn: "LIBERIA",
    isoAlpha2: "LR",
    isoAlpha3: "LBR",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 434,
    name: "ЛИБИЯ",
    nameEn: "LIBYAN ARAB JAMAHIRIYA",
    isoAlpha2: "LY",
    isoAlpha3: "LBY",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 422,
    name: "ЛИВАН",
    nameEn: "LEBANON",
    isoAlpha2: "LB",
    isoAlpha3: "LBN",
    postCodeFormats: "NNNNOOOO",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 440,
    name: "ЛИТВА",
    nameEn: "LITHUANIA",
    isoAlpha2: "LT",
    isoAlpha3: "LTU",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 438,
    name: "ЛИХТЕНЩАЙН",
    nameEn: "LIECHTENSTEIN",
    isoAlpha2: "LI",
    isoAlpha3: "LIE",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 442,
    name: "ЛЮКСЕМБУРГ",
    nameEn: "LUXEMBOURG",
    isoAlpha2: "LU",
    isoAlpha3: "LUX",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 478,
    name: "МАВРИТАНИЯ",
    nameEn: "MAURITANIA",
    isoAlpha2: "MR",
    isoAlpha3: "MRT",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 480,
    name: "МАВРИЦИЙ",
    nameEn: "MAURITIUS",
    isoAlpha2: "MU",
    isoAlpha3: "MUS",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 450,
    name: "МАДАГАСКАР",
    nameEn: "MADAGASCAR",
    isoAlpha2: "MG",
    isoAlpha3: "MDG",
    postCodeFormats: "NNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 175,
    name: "МАЙОТ",
    nameEn: "MAYOTTE",
    isoAlpha2: "YT",
    isoAlpha3: "MYT",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 446,
    name: "МАКАО",
    nameEn: "MACAU",
    isoAlpha2: "MO",
    isoAlpha3: "MAC",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 454,
    name: "МАЛАВИ",
    nameEn: "MALAWI",
    isoAlpha2: "MW",
    isoAlpha3: "MWI",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 458,
    name: "МАЛАЙЗИЯ",
    nameEn: "MALAYSIA",
    isoAlpha2: "MY",
    isoAlpha3: "MYS",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 462,
    name: "МАЛДИВИ",
    nameEn: "MALDIVES",
    isoAlpha2: "MV",
    isoAlpha3: "MDV",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 466,
    name: "МАЛИ",
    nameEn: "MALI",
    isoAlpha2: "ML",
    isoAlpha3: "MLI",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 581,
    name: "МАЛКИ ДАЛЕЧНИ ОСТРОВИ НА САЩ",
    nameEn: "UNITED STATES MINOR OUTLYING ISLANDS",
    isoAlpha2: "UM",
    isoAlpha3: "UMI",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 470,
    name: "МАЛТА",
    nameEn: "MALTA",
    isoAlpha2: "MT",
    isoAlpha3: "MLT",
    postCodeFormats: "AAANNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 504,
    name: "МАРОКО",
    nameEn: "MOROCCO",
    isoAlpha2: "MA",
    isoAlpha3: "MAR",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 474,
    name: "МАРТИНИКА",
    nameEn: "MARTINIQUE",
    isoAlpha2: "MQ",
    isoAlpha3: "MTQ",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 584,
    name: "МАРШАЛОВИ ОСТРОВИ",
    nameEn: "MARSHALL ISLANDS",
    isoAlpha2: "MH",
    isoAlpha3: "MHL",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 484,
    name: "МЕКСИКО",
    nameEn: "MEXICO",
    isoAlpha2: "MX",
    isoAlpha3: "MEX",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 104,
    name: "МИАНМАР",
    nameEn: "MYANMAR",
    isoAlpha2: "MM",
    isoAlpha3: "MMR",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 583,
    name: "МИКРОНЕЗИЯ",
    nameEn: "MICRONESIA, FEDERATED STATES OF",
    isoAlpha2: "FM",
    isoAlpha3: "FSM",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 508,
    name: "МОЗАМБИК",
    nameEn: "MOZAMBIQUE",
    isoAlpha2: "MZ",
    isoAlpha3: "MOZ",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 498,
    name: "МОЛДОВА",
    nameEn: "MOLDOVA, REPUBLIC OF",
    isoAlpha2: "MD",
    isoAlpha3: "MDA",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 492,
    name: "МОНАКО",
    nameEn: "MONACO",
    isoAlpha2: "MC",
    isoAlpha3: "MCO",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 496,
    name: "МОНГОЛИЯ",
    nameEn: "MONGOLIA",
    isoAlpha2: "MN",
    isoAlpha3: "MNG",
    postCodeFormats: "NNNNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 500,
    name: "МОНСЕРАТ",
    nameEn: "MONTSERRAT",
    isoAlpha2: "MS",
    isoAlpha3: "MSR",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 516,
    name: "НАМИБИЯ",
    nameEn: "NAMIBIA",
    isoAlpha2: "NA",
    isoAlpha3: "NAM",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 520,
    name: "НАУРУ",
    nameEn: "NAURU",
    isoAlpha2: "NR",
    isoAlpha3: "NRU",
    postCodeFormats: "NNNNAA",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 524,
    name: "НЕПАЛ",
    nameEn: "NEPAL",
    isoAlpha2: "NP",
    isoAlpha3: "NPL",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 562,
    name: "НИГЕР",
    nameEn: "NIGER",
    isoAlpha2: "NE",
    isoAlpha3: "NER",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 566,
    name: "НИГЕРИЯ",
    nameEn: "NIGERIA",
    isoAlpha2: "NG",
    isoAlpha3: "NGA",
    postCodeFormats: "NNNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 528,
    name: "НИДЕРЛАНДИЯ",
    nameEn: "NETHERLANDS",
    isoAlpha2: "NL",
    isoAlpha3: "NLD",
    postCodeFormats: "NNNNAA",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 558,
    name: "НИКАРАГУА",
    nameEn: "NICARAGUA",
    isoAlpha2: "NI",
    isoAlpha3: "NIC",
    postCodeFormats: "NNNNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 570,
    name: "НИУЕ",
    nameEn: "NIUE",
    isoAlpha2: "NU",
    isoAlpha3: "NIU",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 554,
    name: "НОВА ЗЕЛАНДИЯ",
    nameEn: "NEW ZEALAND",
    isoAlpha2: "NZ",
    isoAlpha3: "NZL",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 540,
    name: "НОВА КАЛЕДОНИЯ",
    nameEn: "NEW CALEDONIA",
    isoAlpha2: "NC",
    isoAlpha3: "NCL",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 578,
    name: "НОРВЕГИЯ",
    nameEn: "NORWAY",
    isoAlpha2: "NO",
    isoAlpha3: "NOR",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 74,
    name: "НОРВЕГИЯ БУВЕ",
    nameEn: "BOUVET ISLAND",
    isoAlpha2: "BV",
    isoAlpha3: "BVT",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 784,
    name: "ОБЕДИНЕНИ АРАБСКИ ЕМИРСТВА",
    nameEn: "UNITED ARAB EMIRATES",
    isoAlpha2: "AE",
    isoAlpha3: "ARE",
    postCodeFormats: "N",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 248,
    name: "ОЛАНД",
    nameEn: "ALAND ISLANDS",
    isoAlpha2: "AX",
    isoAlpha3: "ALA",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 512,
    name: "ОМАН",
    nameEn: "OMAN",
    isoAlpha2: "OM",
    isoAlpha3: "OMN",
    postCodeFormats: "NNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 833,
    name: "ОСТРОВ МАН",
    nameEn: "ISLE OF MAN",
    isoAlpha2: "IM",
    isoAlpha3: "IMN",
    postCodeFormats: "ANNAA,A??NAA,AAN?NAA",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 574,
    name: "ОСТРОВ НОРФОЛК",
    nameEn: "NORFOLK ISLAND",
    isoAlpha2: "NF",
    isoAlpha3: "NFK",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 184,
    name: "ОСТРОВИ КУК",
    nameEn: "COOK ISLANDS",
    isoAlpha2: "CK",
    isoAlpha3: "COK",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 334,
    name: "ОСТРОВИ ХЪРД И МАКДОНАЛД",
    nameEn: "HEARD AND MC DONALD ISLANDS",
    isoAlpha2: "HM",
    isoAlpha3: "HMD",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 586,
    name: "ПАКИСТАН",
    nameEn: "PAKISTAN",
    isoAlpha2: "PK",
    isoAlpha3: "PAK",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 585,
    name: "ПАЛАУ",
    nameEn: "PALAU",
    isoAlpha2: "PW",
    isoAlpha3: "PLW",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 275,
    name: "ПАЛЕСТИНА",
    nameEn: "PALESTINIAN TERRITORY, OCCUPIED",
    isoAlpha2: "PS",
    isoAlpha3: "PSE",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 591,
    name: "ПАНАМА",
    nameEn: "PANAMA",
    isoAlpha2: "PA",
    isoAlpha3: "PAN",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 598,
    name: "ПАПУА НОВА ГВИНЕЯ",
    nameEn: "PAPUA NEW GUINEA",
    isoAlpha2: "PG",
    isoAlpha3: "PNG",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 600,
    name: "ПАРАГВАЙ",
    nameEn: "PARAGUAY",
    isoAlpha2: "PY",
    isoAlpha3: "PRY",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 604,
    name: "ПЕРУ",
    nameEn: "PERU",
    isoAlpha2: "PE",
    isoAlpha3: "PER",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 612,
    name: "ПИТКЕРН",
    nameEn: "PITCAIRN",
    isoAlpha2: "PN",
    isoAlpha3: "PCN",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 616,
    name: "ПОЛША",
    nameEn: "POLAND",
    isoAlpha2: "PL",
    isoAlpha3: "POL",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "PLN",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 620,
    name: "ПОРТУГАЛИЯ",
    nameEn: "PORTUGAL",
    isoAlpha2: "PT",
    isoAlpha3: "PRT",
    postCodeFormats: "NNNNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 630,
    name: "ПУЕРТО РИКО",
    nameEn: "PUERTO RICO",
    isoAlpha2: "PR",
    isoAlpha3: "PRI",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 178,
    name: "РЕПУБЛИКА КОНГО",
    nameEn: "CONGO, PEOPLE'S REPUBLIC OF",
    isoAlpha2: "CG",
    isoAlpha3: "COG",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 807,
    name: "РЕПУБЛИКА МАКЕДОНИЯ",
    nameEn: "MACEDONIA, FYROM",
    isoAlpha2: "MK",
    isoAlpha3: "MKD",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 53,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 638,
    name: "РЕЮНИОН",
    nameEn: "REUNION",
    isoAlpha2: "RE",
    isoAlpha3: "REU",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 646,
    name: "РУАНДА",
    nameEn: "RWANDA",
    isoAlpha2: "RW",
    isoAlpha3: "RWA",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 642,
    name: "РУМЪНИЯ",
    nameEn: "ROMANIA",
    isoAlpha2: "RO",
    isoAlpha3: "ROU",
    postCodeFormats: "NNNNNN",
    requireState: false,
    addressType: 1,
    currencyCode: "RON",
    defaultOfficeId: null,
    streetTypes: "str.,ale.,int.,fdt.,pta.,bld.,drm.,cal.,sos.",
    streetTypesEn: "str.,ale.,int.,fdt.,pta.,bld.,drm.,cal.,sos.",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 1,
  },
  {
    id: 643,
    name: "РУСИЯ",
    nameEn: "RUSSIAN FEDERATION",
    isoAlpha2: "RU",
    isoAlpha3: "RUS",
    postCodeFormats: "NNNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 710,
    name: "РЮА",
    nameEn: "SOUTH AFRICA",
    isoAlpha2: "ZA",
    isoAlpha3: "ZAF",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 882,
    name: "САМОА",
    nameEn: "SAMOA",
    isoAlpha2: "WS",
    isoAlpha3: "WSM",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 674,
    name: "САН МАРИНО",
    nameEn: "SAN MARINO",
    isoAlpha2: "SM",
    isoAlpha3: "SMR",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 678,
    name: "САО ТОМЕ И ПРИНСИПИ",
    nameEn: "SAO TOME AND PRINCIPE",
    isoAlpha2: "ST",
    isoAlpha3: "STP",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 682,
    name: "САУДИТСКА АРАБИЯ",
    nameEn: "SAUDI ARABIA",
    isoAlpha2: "SA",
    isoAlpha3: "SAU",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 840,
    name: "САЩ",
    nameEn: "UNITED STATES",
    isoAlpha2: "US",
    isoAlpha3: "USA",
    postCodeFormats: "NNNNN",
    requireState: true,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 748,
    name: "СВАЗИЛЕНД",
    nameEn: "SWAZILAND",
    isoAlpha2: "SZ",
    isoAlpha3: "SWZ",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 744,
    name: "СВАЛБАРД И ЯН МАЙЕН",
    nameEn: "SVALBARD AND JAN MAYEN ISLANDS",
    isoAlpha2: "SJ",
    isoAlpha3: "SJM",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 654,
    name: "СВЕТА ЕЛЕНА",
    nameEn: "ST. HELENA",
    isoAlpha2: "SH",
    isoAlpha3: "SHN",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 408,
    name: "СЕВЕРНА КОРЕЯ",
    nameEn: "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF",
    isoAlpha2: "KP",
    isoAlpha3: "PRK",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 580,
    name: "СЕВЕРНИ МАРИАНСКИ ОСТРОВИ",
    nameEn: "NORTHERN MARIANA ISLANDS",
    isoAlpha2: "MP",
    isoAlpha3: "MNP",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 670,
    name: "СЕЙНТ ВИНСЪНТ И ГРЕНАДИНИ",
    nameEn: "SAINT VINCENT AND THE GRENADINES",
    isoAlpha2: "VC",
    isoAlpha3: "VCT",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 659,
    name: "СЕЙНТ КИТС И НЕВИС",
    nameEn: "SAINT KITTS AND NEVIS",
    isoAlpha2: "KN",
    isoAlpha3: "KNA",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 662,
    name: "СЕЙНТ ЛУСИЯ",
    nameEn: "SAINT LUCIA",
    isoAlpha2: "LC",
    isoAlpha3: "LCA",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 690,
    name: "СЕЙШЕЛСКИ ОСТРОВИ",
    nameEn: "SEYCHELLES",
    isoAlpha2: "SC",
    isoAlpha3: "SYC",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 652,
    name: "СЕН БАРТЕЛМИ",
    nameEn: "SAINT BARTHELEMY",
    isoAlpha2: "BL",
    isoAlpha3: "BLM",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 663,
    name: "СЕН МАРТЕН",
    nameEn: "SAINT MARTIN",
    isoAlpha2: "MF",
    isoAlpha3: "MAF",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 666,
    name: "СЕН ПИЕР И МИКЕЛОН",
    nameEn: "ST. PIERRE AND MIQUELON",
    isoAlpha2: "PM",
    isoAlpha3: "SPM",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 686,
    name: "СЕНЕГАЛ",
    nameEn: "SENEGAL",
    isoAlpha2: "SN",
    isoAlpha3: "SEN",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 694,
    name: "СИЕРА ЛЕОНЕ",
    nameEn: "SIERRA LEONE",
    isoAlpha2: "SL",
    isoAlpha3: "SLE",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 702,
    name: "СИНГАПУР",
    nameEn: "SINGAPORE",
    isoAlpha2: "SG",
    isoAlpha3: "SGP",
    postCodeFormats: "NNNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 760,
    name: "СИРИЯ",
    nameEn: "SYRIAN ARAB REPUBLIC",
    isoAlpha2: "SY",
    isoAlpha3: "SYR",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 703,
    name: "СЛОВАКИЯ",
    nameEn: "SLOVAKIA (SLOVAK REPUBLIC)",
    isoAlpha2: "SK",
    isoAlpha3: "SVK",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "EUR",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 705,
    name: "СЛОВЕНИЯ",
    nameEn: "SLOVENIA",
    isoAlpha2: "SI",
    isoAlpha3: "SVN",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "EUR",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 90,
    name: "СОЛОМОНОВИ ОСТРОВИ",
    nameEn: "SOLOMON ISLANDS",
    isoAlpha2: "SB",
    isoAlpha3: "SLB",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 706,
    name: "СОМАЛИЯ",
    nameEn: "SOMALIA",
    isoAlpha2: "SO",
    isoAlpha3: "SOM",
    postCodeFormats: "NNNNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 736,
    name: "СУДАН",
    nameEn: "SUDAN",
    isoAlpha2: "SD",
    isoAlpha3: "SDN",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 740,
    name: "СУРИНАМ",
    nameEn: "SURINAME",
    isoAlpha2: "SR",
    isoAlpha3: "SUR",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 688,
    name: "СЪРБИЯ",
    nameEn: "SERBIA",
    isoAlpha2: "RS",
    isoAlpha3: "SRB",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 762,
    name: "ТАДЖИКИСТАН",
    nameEn: "TAJIKISTAN",
    isoAlpha2: "TJ",
    isoAlpha3: "TJK",
    postCodeFormats: "NNNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 158,
    name: "ТАЙВАН",
    nameEn: "TAIWAN",
    isoAlpha2: "TW",
    isoAlpha3: "TWN",
    postCodeFormats: "NNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 764,
    name: "ТАЙЛАНД",
    nameEn: "THAILAND",
    isoAlpha2: "TH",
    isoAlpha3: "THA",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 834,
    name: "ТАНЗАНИЯ",
    nameEn: "TANZANIA, UNITED REPUBLIC OF",
    isoAlpha2: "TZ",
    isoAlpha3: "TZA",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 768,
    name: "ТОГО",
    nameEn: "TOGO",
    isoAlpha2: "TG",
    isoAlpha3: "TGO",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 772,
    name: "ТОКЕЛАУ",
    nameEn: "TOKELAU",
    isoAlpha2: "TK",
    isoAlpha3: "TKL",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 776,
    name: "ТОНГА",
    nameEn: "TONGA",
    isoAlpha2: "TO",
    isoAlpha3: "TON",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 780,
    name: "ТРИНИДАД И ТОБАГО",
    nameEn: "TRINIDAD AND TOBAGO",
    isoAlpha2: "TT",
    isoAlpha3: "TTO",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 798,
    name: "ТУВАЛУ",
    nameEn: "TUVALU",
    isoAlpha2: "TV",
    isoAlpha3: "TUV",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 788,
    name: "ТУНИС",
    nameEn: "TUNISIA",
    isoAlpha2: "TN",
    isoAlpha3: "TUN",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 795,
    name: "ТУРКМЕНИСТАН",
    nameEn: "TURKMENISTAN",
    isoAlpha2: "TM",
    isoAlpha3: "TKM",
    postCodeFormats: "NNNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 792,
    name: "ТУРЦИЯ",
    nameEn: "TURKEY",
    isoAlpha2: "TR",
    isoAlpha3: "TUR",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 796,
    name: "ТЪРКС И КАЙКОС",
    nameEn: "TURKS AND CAICOS ISLANDS",
    isoAlpha2: "TC",
    isoAlpha3: "TCA",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 800,
    name: "УГАНДА",
    nameEn: "UGANDA",
    isoAlpha2: "UG",
    isoAlpha3: "UGA",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 860,
    name: "УЗБЕКИСТАН",
    nameEn: "UZBEKISTAN",
    isoAlpha2: "UZ",
    isoAlpha3: "UZB",
    postCodeFormats: "NNNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 804,
    name: "УКРАЙНА",
    nameEn: "UKRAINE",
    isoAlpha2: "UA",
    isoAlpha3: "UKR",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 348,
    name: "УНГАРИЯ",
    nameEn: "HUNGARY",
    isoAlpha2: "HU",
    isoAlpha3: "HUN",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "HUF",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 876,
    name: "УОЛИС И ФУТУНА",
    nameEn: "WALLIS AND FUTUNA ISLANDS",
    isoAlpha2: "WF",
    isoAlpha3: "WLF",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 858,
    name: "УРУГВАЙ",
    nameEn: "URUGUAY",
    isoAlpha2: "UY",
    isoAlpha3: "URY",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 234,
    name: "ФАРЬОРСКИ ОСТРОВИ",
    nameEn: "FAROE ISLANDS",
    isoAlpha2: "FO",
    isoAlpha3: "FRO",
    postCodeFormats: "NNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 242,
    name: "ФИДЖИ",
    nameEn: "FIJI",
    isoAlpha2: "FJ",
    isoAlpha3: "FJI",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 608,
    name: "ФИЛИПИНИ",
    nameEn: "PHILIPPINES",
    isoAlpha2: "PH",
    isoAlpha3: "PHL",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 246,
    name: "ФИНЛАНДИЯ",
    nameEn: "FINLAND",
    isoAlpha2: "FI",
    isoAlpha3: "FIN",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 238,
    name: "ФОЛКЛЕНДСКИ ОСТРОВИ",
    nameEn: "FALKLAND ISLANDS (MALVINAS)",
    isoAlpha2: "FK",
    isoAlpha3: "FLK",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 250,
    name: "ФРАНЦИЯ",
    nameEn: "FRANCE",
    isoAlpha2: "FR",
    isoAlpha3: "FRA",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 254,
    name: "ФРЕНСКА ГВИАНА",
    nameEn: "FRENCH GUIANA",
    isoAlpha2: "GF",
    isoAlpha3: "GUF",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 258,
    name: "ФРЕНСКА ПОЛИНЕЗИЯ",
    nameEn: "FRENCH POLYNESIA",
    isoAlpha2: "PF",
    isoAlpha3: "PYF",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 260,
    name: "ФРЕНСКИ ЮЖНИ И АНТАРКТИЧЕСКИ ТЕРИТОРИИ",
    nameEn: "FRENCH SOUTHERN TERRITORIES",
    isoAlpha2: "TF",
    isoAlpha3: "ATF",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 332,
    name: "ХАИТИ",
    nameEn: "HAITI",
    isoAlpha2: "HT",
    isoAlpha3: "HTI",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 530,
    name: "ХОЛАНДСКИ АНТИЛИ",
    nameEn: "NETHERLANDS ANTILLES",
    isoAlpha2: "AN",
    isoAlpha3: "ANT",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 340,
    name: "ХОНДУРАС",
    nameEn: "HONDURAS",
    isoAlpha2: "HN",
    isoAlpha3: "HND",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 344,
    name: "ХОНКОНГ",
    nameEn: "HONG KONG",
    isoAlpha2: "HK",
    isoAlpha3: "HKG",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 191,
    name: "ХЪРВАТИЯ",
    nameEn: "CROATIA (LOCAL NAME: HRVATSKA)",
    isoAlpha2: "HR",
    isoAlpha3: "HRV",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "HRK",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 140,
    name: "ЦЕНТРАЛНОАФРИКАНСКА РЕПУБЛИКА",
    nameEn: "CENTRAL AFRICAN REPUBLIC",
    isoAlpha2: "CF",
    isoAlpha3: "CAF",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 148,
    name: "ЧАД",
    nameEn: "CHAD",
    isoAlpha2: "TD",
    isoAlpha3: "TCD",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 499,
    name: "ЧЕРНА ГОРА",
    nameEn: "MONTENEGRO",
    isoAlpha2: "ME",
    isoAlpha3: "MNE",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 203,
    name: "ЧЕХИЯ",
    nameEn: "CZECH REPUBLIC",
    isoAlpha2: "CZ",
    isoAlpha3: "CZE",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "CZK",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 152,
    name: "ЧИЛИ",
    nameEn: "CHILE",
    isoAlpha2: "CL",
    isoAlpha3: "CHL",
    postCodeFormats: "NNNNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 756,
    name: "ШВЕЙЦАРИЯ",
    nameEn: "SWITZERLAND",
    isoAlpha2: "CH",
    isoAlpha3: "CHE",
    postCodeFormats: "NNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 752,
    name: "ШВЕЦИЯ",
    nameEn: "SWEDEN",
    isoAlpha2: "SE",
    isoAlpha3: "SWE",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 144,
    name: "ШРИ ЛАНКА",
    nameEn: "SRI LANKA",
    isoAlpha2: "LK",
    isoAlpha3: "LKA",
    postCodeFormats: "NNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 239,
    name: "ЮЖНА ДЖОРДЖИЯ И ЮЖНИ САНДВИЧЕВИ ОСТРОВИ",
    nameEn: "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
    isoAlpha2: "GS",
    isoAlpha3: "SGS",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 410,
    name: "ЮЖНА КОРЕЯ",
    nameEn: "KOREA, REPUBLIC OF",
    isoAlpha2: "KR",
    isoAlpha3: "KOR",
    postCodeFormats: "NNNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 388,
    name: "ЯМАЙКА",
    nameEn: "JAMAICA",
    isoAlpha2: "JM",
    isoAlpha3: "JAM",
    postCodeFormats: "",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
  {
    id: 392,
    name: "ЯПОНИЯ",
    nameEn: "JAPAN",
    isoAlpha2: "JP",
    isoAlpha3: "JPN",
    postCodeFormats: "NNNNNNN",
    requireState: false,
    addressType: 2,
    currencyCode: "",
    defaultOfficeId: 900,
    streetTypes: "",
    streetTypesEn: "",
    complexTypes: "",
    complexTypesEn: "",
    siteNomen: 0,
  },
];
